module.exports={
    apps:[
        {
            name:'giahuystore',
            script:'./index.js',
            env:{
                NODE_ENV:'production',
                PORT:1001
            }
        }
    ]
}